# core/reporter.py
import json

class WazonReporter:
    @staticmethod
    def generate_html_report(mission_results, filename="wazon_audit_report.html"):
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Wazon - BMS Audit Report</title>
            <style>
                body {{ background-color: #121212; color: #00ff00; font-family: monospace; padding: 20px; }}
                h1 {{ color: #ff0055; text-transform: uppercase; }}
                .card {{ border: 1px solid #333; padding: 15px; margin-bottom: 10px; background: #1e1e1e; }}
                .success {{ color: #00ff66; }}
                .error {{ color: #ff3333; }}
            </style>
        </head>
        <body>
            <h1>Wazon - Operational Infiltration Report</h1>
            <p>Generated by Wazon Framework Core</p>
            <hr>
        """
        
        for res in mission_results:
            status_class = "success" if res.get("status") == "success" else "error"
            html_content += f"""
            <div class="card">
                <h3>Target: {res.get('target', 'Unknown')}</h3>
                <p><b>Status:</b> <span class="{status_class}">{res.get('status')}</span></p>
                <p><b>Data:</b> <pre>{json.dumps(res, indent=2)}</pre></p>
            </div>
            """

        html_content += "</body></html>"
        
        with open(filename, "w") as f:
            f.write(html_content)
        print(f"[+] Audit report successfully compiled: {filename}")